default: &default
  railstutorial_url: "https://www.railstutorial.org/"
  railstutorial_help_url: "https://www.railstutorial.org/help"
  railstutorial_book_url: "https://www.railstutorial.org//book"
  railstutorial_contact_url: "https://www.railstutorial.org/contact"
  michaelhartl_url: "https://www.michaelhartl.com/"
  learnenough_url: "https://www.learnenough.com/"
  railstutorial_screencasts_url: "https://screencasts.railstutorial.org/"
  secure_gravatar_url: "https://secure.gravatar.com/avatar/"
  gravatar_emails: "https://gravatar.com/emails"
  host_url: "http://localhost:3000/"
  email_from: "user@realdomain.com"
  protocol: "https"
  users_per_page: 10
  microposts_per_page: 5
  name_user_max_length: 50
  email_user_max_length: 255
  password_min_length: 6
  gravatar_size: 80
  password_reset_expired: 2
  micropost_content_max_length: 140
  micropost_image_max_size: 5
  resize_to_limit_width: 500
  resize_to_limit_height: 500
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
