default: &default
  railstutorial_url: "https://www.railstutorial.org/"
  railstutorial_help_url: "https://www.railstutorial.org/help"
  railstutorial_book_url: "https://www.railstutorial.org//book"
  railstutorial_contact_url: "https://www.railstutorial.org/contact"
  michaelhartl_url: "https://www.michaelhartl.com/"
  learnenough_url: "https://www.learnenough.com/"
  railstutorial_screencasts_url: "https://screencasts.railstutorial.org/"
  secure_gravatar_url: "https://secure.gravatar.com/avatar/"
  name_user_max_length: 50
  email_user_max_length: 255
  password_min_length: 6
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
